### ISSUE TITLE
License missing!

### ISSUE THREAD

**Issue by CDLuminate** [torch/xlua#17]
Hello, the repo `xlua` ships no license, could you please add a explicit `LICENSE` file. Without the `LICENSE` file I cannot make a Debian package.

**Comment by soumith** [comment]
added via https://github.com/torch/xlua/commit/0dd5f4cf085fde4c8658e29b43b2ab7828dcba33

**Comment by CDLuminate** [comment]
Thanks.

**Comment by CDLuminate** [comment]
Thanks.
